export const SET_GLOBAL_ARTICLES = 'SET_GLOBAL_ARTICLES';
export const SET_TAG_ARTICLES = 'SET_TAG_ARTICLES';
export const SET_YOUR_ARTICLES = 'SET_YOUR_ARTICLES';

export const REMOVE_ALL_ARTICLES = 'REMOVE_ALL_ARTICLES';
